name: ci
on:
  push:
    branches:
      - main
      - dev
  pull_request:

env:
  ISOLATION_ID: ${{ github.run_id }}
  DISTRO: bionic
  SAWTOOTH_CORE: ${{ github.workspace }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # needed for `git describe --dirty` when building docker images
        fetch-depth: 0

    - name: Docker version
      run: |
        docker --version
        docker-compose --version

    - name: Build Lint Requirements
      run: |
        docker-compose -f docker/compose/run-lint.yaml build

    - name: Run Lint
      run: |
        # Disabled because of CRB-213
        # docker-compose -f docker/compose/run-lint.yaml up --abort-on-container-exit --exit-code-from lint-python lint-python
        docker-compose -f docker/compose/run-lint.yaml up --abort-on-container-exit --exit-code-from lint-rust lint-rust
        docker-compose -f docker/compose/run-lint.yaml up --abort-on-container-exit --exit-code-from lint-validator lint-validator


  bandit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # needed for `git describe --dirty` when building docker images
        fetch-depth: 0

    - name: Docker version
      run: |
        docker --version
        docker-compose --version

    - name: Build Test Dependencies
      run: |
        docker build -f docker/bandit -t bandit:$ISOLATION_ID .

    - name: Run Bandit
      run: |
        docker run --rm -v $(pwd):/project/sawtooth-core bandit:$ISOLATION_ID run_bandit


  test-sawtooth-core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # needed for `git describe --dirty` when building docker images
        fetch-depth: 0

    - name: Docker version
      run: |
        docker --version
        docker-compose --version

    - name: Build Test Dependencies
      run: |
        python --version
        pip install yq

        # build services one by one instead of
        # docker-compose -f docker/compose/sawtooth-build.yaml build
        # because we run out of disk space in GitHub
        for SERVICE in $(cat docker/compose/sawtooth-build.yaml | ~/.local/bin/yq -r '.services | keys' -y | sed 's/- //'); do
            echo "INFO: Will build $SERVICE"

            docker-compose -f docker/compose/sawtooth-build.yaml build $SERVICE

            # remove intermediary images
            for IMAGE in $(docker images | grep "<none>" | tr -s ' ' | cut -f3 -d ' '); do
                echo "INFO: Removing intermediary image $IMAGE"
                docker rmi $IMAGE
            done
        done

        echo "INFO: Docker images under test"
        docker images

    - name: Run Tests
      run: |
        INSTALL_TYPE="" ./bin/run_tests
