name: creditcoin-processor

on:
  push:
    branches: dev
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-bionic

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      run: |
        pushd families/creditcoin

        sudo ./scripts/setup-dependencies.sh
        sudo ./scripts/setup-rust.sh

    - name: Lint with clippy
      run: |
        pushd families/creditcoin/ccprocessor-rust

        cargo clippy -- --cfg test -D warnings

        popd

#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Build
#      run: |
#        pushd families/creditcoin
#        docker build -t gluwa/creditcoin-processor .
#        popd
